### ISSUE TITLE
FR: add function to format date for "Created:" field

### ISSUE THREAD

**Issue by Fuco1** [jorgenschaefer/legalese#2]
Would you be interested in adding such a function?  An example implementation is here

```elisp
(defun legalese-date (&optional time)
  "Insert date formatted as Xth Month Year."
  (let* ((day (format-time-string "%e" time))
         (day-ordinal-suffix (diary-ordinal-suffix (string-to-number day)))
         (month-and-year (format-time-string " %B %Y")))
    (concat day day-ordinal-suffix month-and-year)))
```

Produces dates such as "1st August 2015", "12th June 2014", "3rd May 1999" etc... has dependency on `diary`, which however is built-in.

**Comment by jorgenschaefer** [comment]
Thank you! That sounds like a good idea to me, as long as the default stays the same as it is right now.

**Comment by Fuco1** [comment]
By default it doesn't create the `Created:` field, so basically, users would need to add that to the template.  Is that what you mean?  I think in emacs lisp this is prefered, many (155) of the built-in packages have the field for example.

**Comment by jorgenschaefer** [comment]
The `Created` field [is optional](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html), yes. :-) Hm. I guess I wouldn't mind it to be there by default if the default date field is either `YYYY-MM-DD` or `DD mmm YYYY` (as in that reference).

**Comment by Fuco1** [comment]
So let's add a customize with the following options:

* `nil` (default?) - no date
* ISO timestamp (default?) - YYYY-MM-DD
* Wordy timestamp - DDth <full month> YYYY
* String - format string for `format-time-string`

According to that, the variable `legalese-date` would be pre-filled (let-bound).  We can add the `Created:` field to the emacs lisp default template by checking if `legalese-date` is non-nil.

The problem originally came up for me because that is no format for the ordinal suffix (some languages provide it and format the numbers with that as well, granted, english only).  We could create our own format string with this option added but that is completely unnecessary overkill.

**Comment by jorgenschaefer** [comment]
Sounds good to me. For simplicity, leave out `nil` and make `"%d %b %Y"` or `"%Y-%m-%d"` the default?
